### ISSUE TITLE
For TTS to work, need libspeechd.so.2 inside the sandbox

### ISSUE THREAD

**Issue by hypevhs** [flathub/dev.vencord.Vesktop#18]
Use cases:
- I want to use the /tts command in text channels.
- I want to use the [VcNarrator](https://vencord.dev/plugins/VcNarrator) Vencord plugin.

These features use the [Web Speech API](https://mdn.github.io/dom-examples/web-speech-api/speak-easy-synthesis/). On Linux, this is gated behind the Electron flag `--enable-speech-dispatcher`.

These features work outside of Flatpak, but not inside.
Why is that? Chromium dynamically loads the Speech Dispatcher library `libspeechd.so.2`. [Chromium source code for proof](https://source.chromium.org/chromium/chromium/src/+/refs/tags/122.0.6261.111:content/browser/speech/tts_linux.cc;l=251). Inside the Flatpak, this library is not included. The host may have it, but that's outside the sandbox.

For me, a very dirty workaround is to copy the host's library directly into the relevant Flatpak runtime:

```
runtime="$(sed -n 's/^runtime=\(.*\)$/\1/p' /var/lib/flatpak/app/dev.vencord.Vesktop/current/active/metadata)"
# runtime is "org.freedesktop.Platform/x86_64/23.08" in my case
sudo cp /usr/lib/libspeechd.so.2 /var/lib/flatpak/runtime/"$runtime"/active/files/lib/x86_64-linux-gnu/libspeechd.so.2
```

I propose that the library be added to the sandbox so that the TTS stuff can easily work as long as the `--enable-speech-dispatcher` flag is passed.

**Comment by hypevhs** [comment]
It is also necessary to add `xdg-run/speech-dispatcher:ro` to the "Other files" section in Flatseal.

**Comment by lewisakura** [comment]
would have to build the library from scratch since it's not available as a shared module in flatpak it seems, see https://github.com/flathub/org.godotengine.Godot/issues/122

**Comment by hypevhs** [comment]
I opened #20

**Comment by lewisakura** [comment]
^ can you try this PR and see if it works for you?

**Comment by hypevhs** [comment]
Well, yes it works for me, I wrote it
