### ISSUE TITLE
it don't work

### ISSUE THREAD

**Issue by Qaus-Sphene** [flathub/dev.vencord.Vesktop#19]
excuse the silly title but it's really that simple
followed the instructions to a T with no errors thrown at me, launched a game (Bayonetta, which i'm sure is on discord's list of detected games) and checked vesktop, nothing
i'm on fedora 40, not sure what other information would be pertinent

**Comment by lewisakura** [comment]
#11, something similar?

**Comment by Qaus-Sphene** [comment]
i think it's _similar but not the same_  because those fixes do nothing for me

**Comment by lewisakura** [comment]
The relevant Flatpak patch hasn't been released, so they won't work. Please watch that issue instead and when it is closed, you can reopen this one if needed.
