### ISSUE TITLE
transparency does not work in the vesktop flatpak

### ISSUE THREAD

**Issue by linux-universe** [flathub/dev.vencord.Vesktop#21]
Related to: https://github.com/Vencord/Vesktop/issues/466

**this issue only exists with the flatpak**

Describe the bug:
when i turn on transparency in vesktop, it only works if another window is behind vesktop, otherwise it is displayed with strange bugs or it is simply black
[transparency-bug.webm](https://github.com/Vencord/Vesktop/assets/130909958/5467d7c9-34db-4927-8522-5af851f43ea7)

To Reproduce:
1. switch to wayland
2. activate transparency with a matching theme
3. notice that the transparency only works in front of another window

Desktop:
- opensuse Aeon
- gnome
- wayland (bug only appears on wayland)
- vesktop 1.5.2

**Comment by Vendicated** [comment]
you were already told upstream that this bug is out of our control. why open a duplicate issue here?
