### ISSUE TITLE
Switch to X11 if Wayland socket disabled

### ISSUE THREAD

**Issue by nyx-lyb3ra** [flathub/dev.vencord.Vesktop#22]
I noticed that since commit 67fad1fcfe50a55136fb2b7344556e70e5843a55, Wayland socket check has been removed. At first, it makes sense to me, since `--ozone-platform-hint=auto` should fall back to X11 if Wayland is not available... but that doesn't seem to be the case.

If you disable the Wayland socket from Flatseal, then Vesktop simply fails to start.

I'm currently passing `--ozone-platform-hint=x11` to somehow negate the flag that you're using, but I think it would be ideal to bring back the Wayland socket check

**Comment by Vendicated** [comment]
good catch, can repro! readded this check via https://github.com/flathub/dev.vencord.Vesktop/pull/23
