### ISSUE TITLE
Support for launching Vesktop with custom flags from vesktop-flags.conf file

### ISSUE THREAD

**Issue by kibirisu** [flathub/dev.vencord.Vesktop#24]
To open Electron / CEF apps under Wayland on my machine with hybrid graphics (Intel + Nvidia) I need to pass additional flags. I'm aware that the app by default is launched with --ozone-platform=wayland. However, in my case, it is required to include --use-angle=vulkan to make things work.

Can this app respect flags read from a conf file like it does Electron, Chromium and many other apps based on these?

**Comment by Vendicated** [comment]
this is not really possible because of the sandbox. you'd have to put the file in `~/.var/app/dev.vencord.Vesktop/config` which is not very accessible

your best bet is overriding the .desktop file to add your own switches there

**Comment by Vendicated** [comment]
do you know of any other flatpaks that provide such functionality, e.g. chromium? would be helpful to see how others solved it

**Comment by OriOnChip** [comment]
> your best bet is overriding the .desktop file to add your own switches there

This worked like a charm. Thanks!

> do you know of any other flatpaks that provide such functionality, e.g. chromium? would be helpful to see how others solved it

[com.spotify.Client](https://github.com/flathub/com.spotify.Client)

**Comment by OriOnChip** [comment]
I'm closing for now because changing the desktop entry file resolve my issue. 

However, I realized that I don't know if that change will be persistent between updates.

**Comment by Vendicated** [comment]
> This worked like a charm. Thanks!

Note that you'll have to repeat this step every time the package updates. Or you could copy the .desktop file to `~/.local/share/applications` and make your edits there and make sure your DE prefers that directory

> com.spotify.Client

yeah exactly like I said, it reads from the flatpak folder. I guess we could do this as well, it's the best that can be done
